import os
import fresh_tomatoes
import media

# find absolute path to csv
path_to_file = os.path.join(os.path.dirname(__file__), 'my-favourite-movies.csv')  # noqa

# Create a list of dictionaries from the csv file containing my
# favrouite movie data. The values in the top row of the csv
# become the keys in each dict, in this case: 'title', 'year',
# 'summary', 'yw-thoughts', 'poster', 'trailer'.
my_movies_data = media.csv_dict_list(path_to_file)


def create_list_of_movies(list_of_movies):
    """ Create a list of movie instances using the class `Movie`.

        Using a function and constructor from media.py, this function
        takes the list of dictionaries generated by `csv_dict_list`
        as its argument. It then loops through each dictionary and
        contructs instrances of the class `Movie` using the dict
        values of 'title', 'year', 'summary', 'yw-thoughts', 'poster',
        'trailer' as the class arguments.

        Args:
            list_of_movies: A list of dictionaries containing
            data about movies. The keys in each dictionary are:
             'title', 'year', 'summary', 'yw-thoughts',
             'poster', 'trailer'.

        Returns:
            A list of instances of the class `Movie` where the
            arguments for each instance of `Movie` are set by
            the key value pairs in the list of dictionaries.
            For example:

                [
                    movie1 = media.Movie("Jackie Brown", "1997",
                        "A kick-ass lady outwits the dudes.",
                        "Awesome movie, thumbs up!",
                        "https://goo.gl/4yna4o",
                        "https://youtu.be/J9Bd4ShuEAw"),
                    movie2 = media.Movie("Princess Mononoke", "1999",
                        "A battle between several faction in magical
                         woods.",
                        "This movie is beautiful.",
                        "https://goo.gl/sERJr1",
                        "https://youtu.be/YOuG8m2RqOs")
                ]
    """
    movie_list = []

    # Loop through list of dictionaries
    for movie in list_of_movies:
        # Instantiate the class `Movie` using the dict values as
        # its arguments
        my_movie = media.Movie(
            (movie['title']),
            (movie['year']),
            (movie['summary']),
            (movie['yw-thoughts']),
            (movie['poster']),
            (movie['trailer'])
        )
        # Add the new `Movie` object to movie_list
        movie_list.append(my_movie)
    return movie_list

# Create a list of instances of the class `Movie` using data
# from csv file
movies = create_list_of_movies(my_movies_data)

# Generate and open HTML webpage, using content from `Movie` objects
fresh_tomatoes.open_movies_page(movies)
